"""add_new_diagnostic_fields_and_methods

Revision ID: 225752c0e6c4
Revises: 
Create Date: 2025-12-05 17:52:29.150244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225752c0e6c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnostics', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('diagnostics', sa.Column('humidity', sa.Float(), nullable=True))
    op.add_column('diagnostics', sa.Column('illumination', sa.Float(), nullable=True))
    op.add_column('diagnostics', sa.Column('quality_grade', sa.Enum('УДОВЛЕТВОРИТЕЛЬНО', 'ДОПУСТИМО', 'ТРЕБУЕТ_МЕР', 'НЕДОПУСТИМО', name='qualitygrade'), nullable=True))
    op.add_column('diagnostics', sa.Column('param3', sa.Float(), nullable=True))
    # SQLite не поддерживает ALTER COLUMN для изменения типа
    # Если метод уже существует как VARCHAR, оставляем как есть
    # Enum будет работать через SQLAlchemy на уровне приложения
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite не поддерживает ALTER COLUMN для изменения типа
    op.drop_column('diagnostics', 'param3')
    op.drop_column('diagnostics', 'quality_grade')
    op.drop_column('diagnostics', 'illumination')
    op.drop_column('diagnostics', 'humidity')
    op.drop_column('diagnostics', 'temperature')
    # ### end Alembic commands ###

