"""add_source_file_to_diagnostics

Revision ID: 59b6f69bb493
Revises: 225752c0e6c4
Create Date: 2025-12-05 18:36:55.732724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b6f69bb493'
down_revision = '225752c0e6c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnostics', sa.Column('source_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnostics', 'source_file')
    # ### end Alembic commands ###

